name: WordPress CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

permissions:
  issues: write

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - name: Install Docker Compose
        run: |
          sudo curl -L "https://github.com/docker/compose/releases/download/v2.3.3/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
          sudo chmod +x /usr/local/bin/docker-compose
          docker-compose --version
        outputs:
          docker-compose-path: /usr/local/bin/docker-compose

  deploy:
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Use Docker Compose From Setup
        run: |
          export PATH=$PATH:${{ needs.setup.outputs.docker-compose-path }}
          docker-compose --version

      - name: Install SSH Key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          known_hosts: ${{ secrets.SSH_KNOWN_HOSTS }}

      - name: Deploy to Oracle Instance
        run: |
          ssh -o StrictHostKeyChecking=no ubuntu@150.136.240.129 '
            mkdir -p /home/ubuntu/flux-2 &&
            cd /home/ubuntu/flux-2 &&
            if [ ! -d ".git" ]; then
              git clone https://github.com/tsengsational/flux-backend-2.git . &&
              git checkout main
            else
              git fetch origin &&
              git reset --hard origin/main
            fi &&
            docker-compose down &&
            docker-compose pull &&
            docker-compose up -d --build &&
            docker-compose ps &&
            docker-compose logs wordpress
          '

      - name: Verify Deployment
        run: |
          curl -s -o /dev/null -w "%{http_code}" http://150.136.240.129:8000/wp-json/wp/v2/posts || true
        continue-on-error: true

      - name: Notify on Failure
        if: failure()
        uses: actions/github-script@v6
        with:
          script: |
            github.rest.issues.create({
              owner: context.repo.owner,
              repo: context.repo.repo,
              title: 'Deployment Failed',
              body: 'The deployment to Oracle instance failed. Please check the logs.'
            })